### PR TITLE
Disallow array parameters in JSONRPC methods

### LINKED ISSUE #13: soroban-rpc: adding optional params breaks clients using params array format
### What version are you using?

`⁠ v20.1.0 ⁠`

### What did you do?

•⁠  ⁠Request the ⁠` simulateTransaction ⁠` endpoint using array format with a single argument in that params list:

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "simulateTransaction",
  "params": ["AAAAAgAAAADRjwIQ/2zB8tzxMB+71MMO4RoHWCBoTUcd+J0PEBHqKAAAAGQAAAF4AAAAAwAAAAAAAAAAAAAAAQAAAAEAAAAA0Y8CEP9swfLc8TAfu9TDDuEaB1ggaE1HHfidDxAR6igAAAAYAAAAAgAAAnMAYXNtAQAAAAEUBGABfgF+YAJ/fgBgAn5+AX5gAAACDQIBaQEwAAABaQFfAAADBgUBAgMDAwUDAQAQBhkDfwFBgIDAAAt/AEGAgMAAC38AQYCAwAALBy8FBm1lbW9yeQIAA2FkZAADAV8ABgpfX2RhdGFfZW5kAwELX19oZWFwX2Jhc2UDAgqMAgVdAgF/AX4CQAJAIAGnQf8BcSICQcAARg0AAkAgAkEGRg0AQgEhA0KDkICAgAEhAQwCCyABQgiIIQFCACEDDAELQgAhAyABEICAgIAAIQELIAAgATcDCCAAIAM3AwALmQEBAX8jgICAgABBIGsiAiSAgICAACACQRBqIAAQgoCAgAACQAJAIAIoAhANACACKQMYIQAgAiABEIKAgIAAIAIpAwCnDQAgACACKQMIfCIBIABUDQECQAJAIAFC//////////8AVg0AIAFCCIZCBoQhAAwBCyABEIGAgIAAIQALIAJBIGokgICAgAAgAA8LAAALEISAgIAAAAsJABCFgICAAAALBAAAAAsCAAsASw5jb250cmFjdHNwZWN2MAAAAAAAAAAAAAAAA2FkZAAAAAACAAAAAAAAAAFhAAAAAAAABgAAAAAAAAABYgAAAAAAAAYAAAABAAAABgAeEWNvbnRyYWN0ZW52bWV0YXYwAAAAAAAAABQAAAAAAG8OY29udHJhY3RtZXRhdjAAAAAAAAAABXJzdmVyAAAAAAAABjEuNzQuMQAAAAAAAAAAAAhyc3Nka3ZlcgAAAC8yMC4wLjMjOTNiMDllNDJlNGVmYTg0MWNiZDAzNGMwYmZmMGRjMzYyNzY1MDg2YwAAAAAAAAAAAAAAAAAA"]
}
```

### What did you expect to see?

The request to be accepted as it is with soroban-rpc `v20.0.2`.

### What did you see instead?

```
jsonrpc error: ErrorObject { code: InvalidParams, message: "invalid parameters", data: Some(RawValue("[-32602] got 1 parameters, want 2")) }
```

Also, if I make the same request, but with the params passed as a JSON objected with named fields, it is accepted:

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "simulateTransaction",
  "params": {"transaction":"AAAAAgAAAADRjwIQ/2zB8tzxMB+71MMO4RoHWCBoTUcd+J0PEBHqKAAAAGQAAAF4AAAAAgAAAAAAAAAAAAAAAQAAAAEAAAAA0Y8CEP9swfLc8TAfu9TDDuEaB1ggaE1HHfidDxAR6igAAAAYAAAAAgAAAnMAYXNtAQAAAAEUBGABfgF+YAJ/fgBgAn5+AX5gAAACDQIBaQEwAAABaQFfAAADBgUBAgMDAwUDAQAQBhkDfwFBgIDAAAt/AEGAgMAAC38AQYCAwAALBy8FBm1lbW9yeQIAA2FkZAADAV8ABgpfX2RhdGFfZW5kAwELX19oZWFwX2Jhc2UDAgqMAgVdAgF/AX4CQAJAIAGnQf8BcSICQcAARg0AAkAgAkEGRg0AQgEhA0KDkICAgAEhAQwCCyABQgiIIQFCACEDDAELQgAhAyABEICAgIAAIQELIAAgATcDCCAAIAM3AwALmQEBAX8jgICAgABBIGsiAiSAgICAACACQRBqIAAQgoCAgAACQAJAIAIoAhANACACKQMYIQAgAiABEIKAgIAAIAIpAwCnDQAgACACKQMIfCIBIABUDQECQAJAIAFC//////////8AVg0AIAFCCIZCBoQhAAwBCyABEIGAgIAAIQALIAJBIGokgICAgAAgAA8LAAALEISAgIAAAAsJABCFgICAAAALBAAAAAsCAAsASw5jb250cmFjdHNwZWN2MAAAAAAAAAAAAAAAA2FkZAAAAAACAAAAAAAAAAFhAAAAAAAABgAAAAAAAAABYgAAAAAAAAYAAAABAAAABgAeEWNvbnRyYWN0ZW52bWV0YXYwAAAAAAAAABQAAAAAAG8OY29udHJhY3RtZXRhdjAAAAAAAAAABXJzdmVyAAAAAAAABjEuNzQuMQAAAAAAAAAAAAhyc3Nka3ZlcgAAAC8yMC4wLjMjOTNiMDllNDJlNGVmYTg0MWNiZDAzNGMwYmZmMGRjMzYyNzY1MDg2YwAAAAAAAAAAAAAAAAAA"}
}
```

### Discussion

This issue has been discussed in these places:
- Discord: https://discord.com/channels/897514728459468821/1187260422689132585
- Slack: https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1703122700787559

This issue arises because in v20.1.0 the soroban-rpc's simulateTransaction endpoint had a new optional parameter added to it's request object:
- https://github.com/stellar/soroban-tools/pull/1131

The jsonrpc specification doesn't say how optional parameters should behave, it is implementation specific, and the jsonrpc library in use by the soroban-rpc allows optional parameters when the `params` are defined as a JSON object, but requires them when the `params` are defined as a JSON array.

From discussions on the jsonrpc mailing list it sounds like it is common for jsonrpc implementations to allow optional parameters to be ommitted in the params (see https://groups.google.com/g/json-rpc/c/n4kiH9yKBww/m/0ssppnkGpv8J), but that behavior isn't supported by the jsonrpc library the soroban-rpc is using.

Until the soroban-rpc's jsonrpc implementation supports omitting optional parameters in the `params` array format, I don't see how we can ever add an optional parameter though, since doing so may break any client that is using array format, as what we saw with the above v20.1.0 release.

cc @Shaptic @mollykarcher

### LINKED ISSUE #40: soroban-rpc: getHealth should not fail if called with an empty parameter array.
Currently if you call `getHealth` with params: `[]`, it throws. For example:
```bash
curl -v \
  -X POST \
  --header "content-type: application/json" \
  http://localhost:8000/soroban/rpc \
  --data-binary '{"jsonrpc":"2.0", "id":2, "method":"getHealth", "params": []}'
```

### PR DESCRIPTION
**Pull request by 2opremio**
### What

Disallow array parameters in JSONRPC methods

### Why

Close #13 Close #40

**Do not merge until we want to cut a protocol 21 release**

### CODE REVIEW

**Review by Shaptic — APPROVED** [review]

**Comment by 2opremio** [comment]
@Shaptic it seems like javascript is still using array parameters. Could that be the case?

**Comment by mollykarcher** [comment]
> @Shaptic it seems like javascript is still using array parameters. Could that be the case?

It looks like it was [updated](https://github.com/stellar/js-stellar-sdk/releases/tag/v11.3.0), so you just need to update the system tests to reference the most recent SDK release

**Comment by 2opremio** [comment]
Uhm, it seems the CLI doesn't like it either ...

**Comment by 2opremio** [comment]
@willemneal Could it be that the CLI uses array arguments in JSONRPC calls?

**Comment by willemneal** [comment]
Here are some of the jsonrpc requests from a trace from the CLI deploying a contract, which all use the array for "params"
```json
[
  {
    "jsonrpc": "2.0",
    "id": 0,
    "method": "getLedgerEntries",
    "params": [
      [
        "AAAAAAAAAADh9C8tjVls3DqO4pComSAu7Uowvdz14Q1ANPs6kFTv6A=="
      ]
    ]
  },
  {
    "jsonrpc": "2.0",
    "id": 0,
    "method": "getTransaction",
    "params": [
      "303066cd68a6e8a669ca3fc22ca60f07011f9c99c4b73c046ca6e72818d207b5"
    ]
  },
  {
    "jsonrpc": "2.0",
    "id": 0,
    "method": "simulateTransaction",
    "params": {
      "transaction": "AAAAAgAAAADh9C8tjVls3DqO4pComSAu7Uowvdz14Q1ANPs6kFTv6AAAAGQAAADOAAAABwAAAAAAAAAAAAAAAQAAAAAAAAAYAAAAAQAAAAAAAAAAAAAAAOH0Ly2NWWzcOo7ikKiZIC7tSjC93PXhDUA0+zqQVO/oTPSTOwMvaooNPLS9FedDzC5S3DQ6BNZLYmDtS17OKIoAAAAAgPljDahC0uEgl8NOZZOM4yWQttNLhzyz5tyKYt0bA5YAAAAAAAAAAAAAAAA="
    }
  },
  {
    "jsonrpc": "2.0",
    "id": 0,
    "method": "sendTransaction",
    "params": [
      "AAAAAgAAAADh9C8tjVls3DqO4pComSAu7Uowvdz14Q1ANPs6kFTv6AAD2uEAAADOAAAABwAAAAAAAAAAAAAAAQAAAAAAAAAYAAAAAQAAAAAAAAAAAAAAAOH0Ly2NWWzcOo7ikKiZIC7tSjC93PXhDUA0+zqQVO/oTPSTOwMvaooNPLS9FedDzC5S3DQ6BNZLYmDtS17OKIoAAAAAgPljDahC0uEgl8NOZZOM4yWQttNLhzyz5tyKYt0bA5YAAAABAAAAAAAAAAEAAAAAAAAAAAAAAADh9C8tjVls3DqO4pComSAu7Uowvdz14Q1ANPs6kFTv6Ez0kzsDL2qKDTy0vRXnQ8wuUtw0OgTWS2Jg7UteziiKAAAAAID5Yw2oQtLhIJfDTmWTjOMlkLbTS4c8s+bcimLdGwOWAAAAAAAAAAEAAAAAAAAAAQAAAAeA+WMNqELS4SCXw05lk4zjJZC200uHPLPm3Ipi3RsDlgAAAAEAAAAGAAAAAXmbAq7ocZCaTIPZo0Kjumf6ulOoMG8FEPT+i5O+lw+/AAAAFAAAAAEALqtnAAAXDAAAAGgAAAAAAANZxAAAAAGQVO/oAAAAQBFkNvKWhKrv0JXUgfELdpRjXtebp4b6NU8yDljeRvNGhtIwPz0lLSXlLctKmSQMYQ7nN3smlMnpk3WsxS3CGAc="
    ]
  }
]
```
Looking at the rust crate it uses `rpc_params![]` which returns an array defined here: https://github.com/paritytech/jsonrpsee/blob/87a37a719a378b0700f519beeee3c21f95bc6495/core/src/client/mod.rs#L216

**Comment by 2opremio** [comment]
Ahh, it's defined in the rpc-client crate. I will try to fix it.

**Comment by 2opremio** [comment]
I think we first need to update the CLI code to use the object parameters. I will create a separate PR for that

**Comment by leighmcculloch** [comment]
Replying to https://github.com/stellar/soroban-rpc/pull/125#issue-2227442542:
> Also, it's a good idea to release an updated CLI version first, to allow users to upgrade before disallowing array parameters for good.

I agree it'd be ideal to release the CLI and for there to be a period of time where the breakage is not experienced so as to reduce it's impact and give folks time to upgrade.

When we planned #121 for this upcoming release we thought that we had already updated every client that was using arrays weeks/months ago, meaning there was plenty of time to pull the plug on arrays. But it'll be pretty rough to pull the plug now if we're only providing a week or two, and we break all existing users.

Maybe that's not a big deal if there's other necessary breaking changes already in play.

**Comment by 2opremio** [comment]
> we thought that we had already updated every client that was using arrays weeks/months ago

I though so too 🤷

**Comment by 2opremio** [comment]
@willemneal will you let me know once the CLI is updated to use the rpc client create version 20.3.5? That should unblock this PR.

Thanks!

**Comment by willemneal** [comment]
@2opremio Here is the PR to update the deps: https://github.com/stellar/soroban-cli/pull/1281

**Pull request merged**
